### PR TITLE
Issue #37: Fixing Xbee comms issue

### LINKED ISSUE #37: Xbee communcation not stable
Xbee communcation does not seem to be stable. A lot of 'invalid frames' are received.

### PR DESCRIPTION
**Pull request by boons605**
Fixes Xbee comms to close #37

### CODE REVIEW

File: CentralUnit/Communication/XbeeNetwork.cs [hunk 1]
```diff
@@ -238,23 +238,27 @@ private XBeePacket CheckPacketComplete(byte[] buffer, int position)
...
                     }
-                }
-            }
 
-            if (packet == null)
-            {
-                Log.Error($"Packet in queue was invalid, data: {BitConverter.ToString(buffer)}");
+                    if (packet == null)
+                    {
+                        //Log.Error($"Packet in queue was invalid");
```
Comment (CptMalfunction) [inline CentralUnit/Communication/XbeeNetwork.cs:258]: this looks like its no longer needed

File: CentralUnit/Communication/XbeeNetwork.cs [hunk 2]
```diff
@@ -238,23 +238,27 @@ private XBeePacket CheckPacketComplete(byte[] buffer, int position)
             {
                 ushort packetLength = (ushort)(((ushort)buffer[1]) << 8);
                 packetLength |= (ushort)buffer[2];
+                packetLength += (ushort)buffer.Count(bt => bt == (byte)SpecialByte.ESCAPE_BYTE);
+                packetLength += 4;
 
-                if (position >= packetLength)
+                if ((position >= packetLength) &&
+                    (packetLength > 0))
```
Comment (CptMalfunction) [inline CentralUnit/Communication/XbeeNetwork.cs:245]: Since you're adding 4 to the packet length at line 242, isnt this always true?

File: CentralUnit/Communication/XbeeNetwork.cs [hunk 3]
```diff
@@ -238,23 +238,27 @@ private XBeePacket CheckPacketComplete(byte[] buffer, int position)
             {
                 ushort packetLength = (ushort)(((ushort)buffer[1]) << 8);
                 packetLength |= (ushort)buffer[2];
+                packetLength += (ushort)buffer.Count(bt => bt == (byte)SpecialByte.ESCAPE_BYTE);
+                packetLength += 4;
```
Comment (CptMalfunction) [inline CentralUnit/Communication/XbeeNetwork.cs:242]: i would like a comment to say where this 4 is coming from

Comment (CptMalfunction) [reply CentralUnit/Communication/XbeeNetwork.cs:242]: or maybe just in general how the packet lengths works, since its a 3 line calculation
